Repository crystal-ameba/ameba, pull requests merged in 2024-10, with the labels that each got.

#474 Guard calls to the `typos` with a mutex
  src/ameba/rule/lint/typos.cr
Labels: bug

#476 Ignore block parameter names starting with `_`
  spec/ameba/rule/naming/block_parameter_name_spec.cr
  src/ameba/rule/naming/block_parameter_name.cr
Labels: false positive

#478 Fix portable variable assignments in Makefile
  Makefile
Labels: infrastructure

#480 Use `make` in CI
  .github/workflows/ci.yml
Labels: refactor, infrastructure

#479 Give the `Makefile` a subtle massage
  Makefile
Labels: refactor, infrastructure

#482 `crystal tool format` with Crystal 1.15.0-dev
  src/ameba/ast/variabling/argument.cr
Labels: refactor

#483 Add `split` and `lines` to the allocating method names in `Performance/ChainedCallWithNoBang` rule
  src/ameba/rule/performance/chained_call_with_no_bang.cr
Labels: enhancement, rule

#484 Cleanups
  .github/workflows/ci.yml
  .gitignore
  Makefile
  README.md
  spec/ameba/ast/scope_spec.cr
  spec/ameba/rule/lint/formatting_spec.cr
  spec/ameba/rule/lint/percent_arrays_spec.cr
  spec/spec_helper.cr
  src/ameba/rule/lint/typos.cr
  src/ameba/rule/naming/block_parameter_name.cr
Labels: refactor

#485 fix(lint): useless assign with method call within a condition
  spec/ameba/rule/lint/useless_assign_spec.cr
  src/ameba/ast/branch.cr
Labels: false positive
