Repository crystal-ameba/ameba, pull requests merged in 2024-11, with the labels that each got.

#490 Optimize code to avoid intermediate array allocations 🚀
  src/ameba/formatter/disabled_formatter.cr
  src/ameba/rule/lint/literal_in_interpolation.cr
  src/ameba/rule/lint/redundant_string_coercion.cr
  src/ameba/rule/lint/shadowing_outer_local_var.cr
  src/ameba/rule/lint/shared_var_in_fiber.cr
  src/ameba/rule/naming/accessor_method_name.cr
  src/ameba/rule/naming/query_bool_methods.cr
  src/ameba/runner.cr
Labels: enhancement, refactor

#494 Use `Mutex` in `JSONFormatter`
  src/ameba/formatter/json_formatter.cr
Labels: bug

#498 Misc refactors
  src/ameba/config.cr
  src/ameba/formatter/base_formatter.cr
  src/ameba/formatter/dot_formatter.cr
  src/ameba/formatter/todo_formatter.cr
Labels: refactor

#495 Add `Nil` return types to methods with side-effects only
  spec/ameba/formatter/todo_formatter_spec.cr
  src/ameba/cli/cmd.cr
  src/ameba/formatter/base_formatter.cr
  src/ameba/formatter/disabled_formatter.cr
  src/ameba/formatter/dot_formatter.cr
  src/ameba/formatter/explain_formatter.cr
  src/ameba/formatter/flycheck_formatter.cr
  src/ameba/formatter/json_formatter.cr
  src/ameba/formatter/todo_formatter.cr
  src/ameba/presenter/rule_collection_presenter.cr
  src/ameba/presenter/rule_presenter.cr
  src/ameba/runner.cr
Labels: refactor

#499 Raise when config is not a `Hash`
  spec/ameba/config_spec.cr
  src/ameba/config.cr
Labels: bug

#501 While passing file through `STDIN` we should lint just that
  src/ameba/config.cr
Labels: bug

#506 Allow passing single `-` argument as a means to accept file via `STDIN`
  spec/ameba/cli/cmd_spec.cr
  src/ameba/cli/cmd.cr
Labels: enhancement

#515 Disable autocorrection when source is passed through `STDIN`
  spec/ameba/cli/cmd_spec.cr
  src/ameba/cli/cmd.cr
Labels: bug, autocorrect

#510 Add `Lint/RequireParentheses`
  spec/ameba/rule/lint/require_parentheses_spec.cr
  src/ameba/rule/lint/require_parentheses.cr
Labels: rule

#512 Add `Lint/TrailingRescueException`
  spec/ameba/rule/lint/trailing_rescue_exception_spec.cr
  src/ameba/rule/lint/trailing_rescue_exception.cr
Labels: rule
