Repository crystal-ameba/ameba, pull requests merged in 2024-12, with the labels that each got.

#524 Add `Style/MultilineCurlyBlock`
  spec/ameba/rule/style/multiline_curly_block_spec.cr
  src/ameba/rule/documentation/documentation_admonition.cr
  src/ameba/rule/style/multiline_curly_block.cr
Labels: rule

#527 Add GitHub Actions formatter
  spec/ameba/formatter/github_actions_formatter_spec.cr
  src/ameba/config.cr
  src/ameba/formatter/github_actions_formatter.cr
Labels: feature

#528 Sort sources and issues before passing them to the formatter
  src/ameba/runner.cr
Labels: bug

#529 Make issue messages moar Markdown-friendly
  spec/ameba/rule/lint/hash_duplicated_key_spec.cr
  spec/ameba/rule/lint/percent_arrays_spec.cr
  spec/ameba/rule/lint/rand_zero_spec.cr
  spec/ameba/rule/lint/shadowed_exception_spec.cr
  spec/ameba/rule/lint/spec_filename_spec.cr
  spec/ameba/rule/lint/typos_spec.cr
  spec/ameba/rule/naming/accessor_method_name_spec.cr
  spec/ameba/rule/naming/constant_names_spec.cr
  spec/ameba/rule/naming/filename_spec.cr
  spec/ameba/rule/naming/method_names_spec.cr
  spec/ameba/rule/naming/predicate_name_spec.cr
  spec/ameba/rule/naming/query_bool_methods_spec.cr
  spec/ameba/rule/naming/type_names_spec.cr
  spec/ameba/rule/naming/variable_names_spec.cr
  spec/ameba/rule/style/large_numbers_spec.cr
  spec/ameba/rule/style/unless_else_spec.cr
  spec/ameba/rule/style/while_true_spec.cr
  src/ameba/rule/lint/hash_duplicated_key.cr
  src/ameba/rule/lint/percent_arrays.cr
  src/ameba/rule/lint/rand_zero.cr
  src/ameba/rule/lint/shadowed_exception.cr
  src/ameba/rule/lint/spec_filename.cr
  src/ameba/rule/lint/typos.cr
  src/ameba/rule/naming/accessor_method_name.cr
  src/ameba/rule/naming/constant_names.cr
  src/ameba/rule/naming/filename.cr
  src/ameba/rule/naming/method_names.cr
  src/ameba/rule/naming/predicate_name.cr
  src/ameba/rule/naming/query_bool_methods.cr
  src/ameba/rule/naming/type_names.cr
  src/ameba/rule/naming/variable_names.cr
  src/ameba/rule/style/large_numbers.cr
  src/ameba/rule/style/unless_else.cr
  src/ameba/rule/style/while_true.cr
Labels: enhancement, refactor

#530 Fix `DotFormatter` failures count
  spec/ameba/formatter/dot_formatter_spec.cr
  src/ameba/formatter/dot_formatter.cr
Labels: bug

#507 Add `Lint/UnusedComparison` and `Lint/UnusedLiteral`
  spec/ameba/rule/lint/unused_comparison_spec.cr
  spec/ameba/rule/lint/unused_literal_spec.cr
  src/ameba/ast/visitors/implicit_return_visitor.cr
  src/ameba/rule/lint/unused_comparison.cr
  src/ameba/rule/lint/unused_literal.cr
Labels: rule

#531 Add support for summaries in `GitHubActionsFormatter`
  spec/ameba/formatter/github_actions_formatter_spec.cr
  src/ameba/formatter/dot_formatter.cr
  src/ameba/formatter/github_actions_formatter.cr
  src/ameba/formatter/util.cr
Labels: enhancement

#533 Fix edge cases with `Lint/UnusedComparison` and `Lint/UnusedLiteral`
  spec/ameba/rule/lint/unused_comparison_spec.cr
  spec/ameba/rule/lint/unused_literal_spec.cr
  src/ameba/ast/visitors/implicit_return_visitor.cr
  src/ameba/rule/lint/unused_comparison.cr
Labels: bug, rule

#522 Add `Typing/ProcLiteralReturnTypeRestriction`
  spec/ameba/base_spec.cr
  spec/ameba/rule/typing/proc_literal_return_type_restriction_spec.cr
  src/ameba/ast/visitors/node_visitor.cr
  src/ameba/rule/typing/proc_literal_return_type_restriction.cr
Labels: rule
