Repository crystal-ameba/ameba, pull requests merged in 2025-06, with the labels that each got.

#616 Remove noise from `--gen-config`
  spec/ameba/formatter/todo_formatter_spec.cr
  src/ameba/formatter/todo_formatter.cr
Labels: refactor

#630 Fix regression in `Lint/LiteralsComparison`
  spec/ameba/rule/lint/literals_comparison_spec.cr
  src/ameba/rule/lint/literals_comparison.cr
Labels: bug, rule

#627 Do not report CRLF sequences in `Layout/TrailingWhitespace` rule
  spec/ameba/rule/layout/trailing_whitespace_spec.cr
  src/ameba/source.cr
Labels: false positive

#629 Fix `select` expression omissions
  spec/ameba/ast/branch_spec.cr
  spec/ameba/ast/util_spec.cr
  spec/ameba/ast/visitors/counting_visitor_spec.cr
  spec/ameba/rule/lint/useless_assign_spec.cr
  src/ameba/ast/branch.cr
  src/ameba/ast/util.cr
  src/ameba/ast/visitors/counting_visitor.cr
  src/ameba/ast/visitors/redundant_control_expression_visitor.cr
Labels: false positive, refactor

#635 Ignore Regex character types in `Style/HeredocEscape`
  spec/ameba/rule/style/heredoc_escape_spec.cr
  src/ameba/rule/style/heredoc_escape.cr
Labels: false positive

#637 Constantinize issue messages in `Lint/RedundantWithIndex`
  spec/ameba/rule/lint/redundant_with_index_spec.cr
  src/ameba/rule/lint/redundant_with_index.cr
Labels: refactor, rule

#638 Report only static literals in `Lint/LiteralInInterpolation`
  spec/ameba/rule/lint/literal_in_interpolation_spec.cr
  src/ameba/rule/lint/literal_in_interpolation.cr
Labels: false positive

#639 Add `Lint/UselessVisibilityModifier` rule
  spec/ameba/rule/lint/useless_visibility_modifier_spec.cr
  src/ameba/rule/lint/useless_visibility_modifier.cr
Labels: rule

#633 Skip dynamic literals comparison in `Lint/LiteralsComparison`
  spec/ameba/ast/util_spec.cr
  spec/ameba/rule/lint/literals_comparison_spec.cr
  src/ameba/ast/util.cr
  src/ameba/rule/lint/literals_comparison.cr
Labels: false positive

#641 Add git sha to the printed version
  src/ameba.cr
  src/ameba/cli/cmd.cr
  src/ameba/version.cr
Labels: enhancement

#646 Consolidate unused expression rules into one `Lint/UnusedExpression` rule
  spec/ameba/rule/lint/unused_class_variable_access_spec.cr
  spec/ameba/rule/lint/unused_comparison_spec.cr
  spec/ameba/rule/lint/unused_expression_spec.cr
  spec/ameba/rule/lint/unused_generic_or_union_spec.cr
  spec/ameba/rule/lint/unused_instance_variable_access_spec.cr
  spec/ameba/rule/lint/unused_literal_spec.cr
  spec/ameba/rule/lint/unused_local_variable_access_spec.cr
  spec/ameba/rule/lint/unused_pseudo_method_call_spec.cr
  spec/ameba/rule/lint/unused_self_access_spec.cr
  src/ameba/ast/visitors/implicit_return_visitor.cr
  src/ameba/rule/lint/unused_class_variable_access.cr
  src/ameba/rule/lint/unused_comparison.cr
  src/ameba/rule/lint/unused_expression.cr
  src/ameba/rule/lint/unused_generic_or_union.cr
  src/ameba/rule/lint/unused_instance_variable_access.cr
  src/ameba/rule/lint/unused_literal.cr
  src/ameba/rule/lint/unused_local_variable_access.cr
  src/ameba/rule/lint/unused_pseudo_method_call.cr
  src/ameba/rule/lint/unused_self_access.cr
Labels: refactor, rule

#649 Add `exclude_multiline` setting to `Style/ParenthesesAroundCondition` rule
  spec/ameba/rule/style/parentheses_around_condition_spec.cr
  src/ameba/rule/style/parentheses_around_condition.cr
Labels: enhancement, rule

#651 Add `Ext::Location#same_line?` helper method
  src/ameba/ext/location.cr
  src/ameba/formatter/github_actions_formatter.cr
  src/ameba/rule/style/guard_clause.cr
  src/ameba/rule/style/multiline_curly_block.cr
  src/ameba/rule/style/parentheses_around_condition.cr
  src/ameba/rule/style/verbose_block.cr
Labels: refactor
