Repository crystal-ameba/ameba, pull requests merged in 2025-01, with the labels that each got.

#541 Add support for linting ECR files (pt. 2)
  README.md
  spec/ameba/source_spec.cr
  src/ameba.cr
  src/ameba/config.cr
  src/ameba/glob_utils.cr
  src/ameba/source.cr
Labels: feature

#544 In case scope queue is empty call the rule with the current scope
  spec/ameba/rule/lint/useless_assign_spec.cr
  src/ameba/ast/visitors/scope_visitor.cr
Labels: refactor

#546 Fix regression re: incorrect glob pattern for folders
  spec/ameba/glob_utils_spec.cr
  src/ameba/glob_utils.cr
Labels: bug

#537 Add `Lint/UnusedGenericOrUnion`
  spec/ameba/rule/lint/unused_generic_or_union_spec.cr
  src/ameba/ast/visitors/implicit_return_visitor.cr
  src/ameba/rule/lint/unused_comparison.cr
  src/ameba/rule/lint/unused_generic_or_union.cr
  src/ameba/rule/lint/unused_literal.cr
Labels: rule

#547 Add `Style/RedundantSelf` rule
  spec/ameba/ast/visitors/scope_calls_with_self_receiver_visitor_spec.cr
  spec/ameba/rule/style/redundant_self_spec.cr
  spec/spec_helper.cr
  src/ameba/ast/visitors/scope_calls_with_self_receiver_visitor.cr
  src/ameba/rule/documentation/documentation_admonition.cr
  src/ameba/rule/lint/unneeded_disable_directive.cr
  src/ameba/rule/style/redundant_self.cr
  src/contrib/read_type_doc.cr
Labels: rule

#558 Add `unstable_sort` to the call name list in `Performance/ChainedCallWithNoBang` rule
  src/ameba/rule/performance/chained_call_with_no_bang.cr
Labels: enhancement

#557 Add ability to ignore `:nodoc:` methods in `Typing` rules
  spec/ameba/ast/util_spec.cr
  spec/ameba/rule/typing/method_parameter_type_restriction_spec.cr
  spec/ameba/rule/typing/method_return_type_restriction_spec.cr
  spec/spec_helper.cr
  src/ameba/ast/util.cr
  src/ameba/rule/typing/method_parameter_type_restriction.cr
  src/ameba/rule/typing/method_return_type_restriction.cr
Labels: enhancement, rule
